# ========== Youtube ==========
http-proxy=http://127.0.0.1:10808
ytdl-raw-options=proxy="http://127.0.0.1:10808",no-check-certificate=
tls-verify=no
ytdl-format=bestvideo[height<=480]+bestaudio/best[height<=480]
# ========== General ==========
autofit=50%
keep-open=yes
cursor-autohide=1000
save-position-on-quit=yes
volume=75

# ========== Interface ==========
osc=no
osd-bar=no
osd-on-seek=no
border=no
osd-font-size=32
msg-level=all=error

# ========== Subtitles ==========
sub-auto=fuzzy
sub-font='Arial'
sub-font-size=40
sub-border-size=1
sub-shadow-color=0.0/0.0/0.0/0.50
sub-shadow-offset=2

# ========== Screenshot ==========
screenshot-format=webp
screenshot-webp-lossless=yes
screenshot-high-bit-depth=yes
screenshot-sw=no

# ========== Decoding & Rendering ==========
profile=high-quality
vo=gpu-next
gpu-api=vulkan
vulkan-async-transfer=yes
vulkan-async-compute=yes
hwdec=no

# ========== Caching (Enabled for HDD) ==========
cache=yes
demuxer-max-bytes=800MiB
demuxer-readahead-secs=300
cache-on-disk=no

# ========== HDR ==========
target-colorspace-hint=yes
target-contrast=auto
target-peak=800
hdr-compute-peak=auto

# ========== Core Playback & Smooth Motion ==========
video-sync=display-resample
tscale=mitchell
video-latency-hacks=no

# ========== Scaling & Downscaling ==========
scale=ewa_lanczos
cscale=ewa_lanczos
dscale=catmull_rom
scale-blur=0.981251

# ========== Dithering ==========
dither=error-diffusion
error-diffusion=sierra-lite
dither-depth=auto

# ========== Antiringing ==========
scale-antiring=0
dscale-antiring=0
cscale-antiring=0

# ========== Debanding ==========
deband=yes
deband-iterations=2
deband-threshold=32
deband-range=16
deband-grain=0

# ========== Upscaling ==========
glsl-shaders="~~/shaders/KrigBilateral2.glsl"
glsl-shaders-append="~~/shaders/FSR.glsl"

# Deband profiles
[deband-strong]
profile-cond=video_out_params and video_out_params.h < 1080
deband-iterations=4
deband-threshold=48
deband-range=24
deband-grain=16

[deband-moderate]
profile-cond=video_out_params and video_out_params.h >= 1080
deband-iterations=2
deband-threshold=32
deband-range=16
deband-grain=0
