# Volume controls
up    no-osd add volume 5; script-binding uosc/flash-volume
down  no-osd add volume -5; script-binding uosc/flash-volume
m     no-osd cycle mute; script-binding uosc/flash-volume

# Seek controls
right        seek 5; script-binding uosc/flash-timeline
left         seek -5; script-binding uosc/flash-timeline
shift+right  seek 30; script-binding uosc/flash-timeline
shift+left   seek -30; script-binding uosc/flash-timeline

# Speed controls
[    no-osd add speed -0.25; script-binding uosc/flash-speed
]    no-osd add speed 0.25; script-binding uosc/flash-speed
\    no-osd set speed 1; script-binding uosc/flash-speed

# Pause indicator

space  cycle pause; script-binding uosc/flash-pause-indicator

# UOSC default menu items
s           script-binding uosc/subtitles
a           script-binding uosc/audio
q           script-binding uosc/stream-quality
p           script-binding uosc/items
c           script-binding uosc/chapters
>           script-binding uosc/next
<           script-binding uosc/prev
alt+>       script-binding uosc/delete-file-next
alt+<       script-binding uosc/delete-file-prev
alt+esc     script-binding uosc/delete-file-quit
o           script-binding uosc/open-file
ctrl+s      async screenshot
alt+i       script-binding uosc/keybinds
O           script-binding uosc/show-in-directory
esc         quit