[services]
gog = False
egs = False
ea_app = False
ubisoft = False
steam = False

[lutris]
library_ignores =
migration_version = 17
width = 960
height = 999
window_x = 20
window_y = 20
maximized = False
selected_category = runner:wine
show_advanced_options = True
hide_client_on_game_start = True
show_tray_icon = False
preferred_theme = dark
auto_update_runtime = False
