[services]
gog = False
egs = False
ea_app = False
ubisoft = False
steam = False

[lutris]
library_ignores = 
migration_version = 17
width = 1280
height = 1359
window_x = 20
window_y = 20
maximized = False
selected_category = category:all
show_advanced_options = True
hide_client_on_game_start = False
show_tray_icon = False
preferred_theme = dark
auto_update_runtime = False
icon_type_gridview = coverart_big
view_sorting_installed_first = True
sidebar_collapsed_sections = 

