[services]
gog = False
egs = False
ea_app = False
ubisoft = False
steam = True

[lutris]
library_ignores = 
migration_version = 17
width = 1920
height = 984
window_x = 45
window_y = 45
maximized = True
selected_category = service:steam
icon_type_gridview = coverart_big
show_advanced_options = True
auto_update_runtime = False
last_library_sync_at = 1784657821
icon_type_gridview_steam = cover
view_type = grid
sidebar_collapsed_sections = 

[list view]
name_column_width = 200
year_column_width = 60
runner_column_width = 120
platform_column_width = 120
lastplayed_column_width = 120
playtime_column_width = 100
installedat_column_width = 120

