[services]
gog = False
egs = False
ea_app = False
ubisoft = False
steam = True

[lutris]
library_ignores = 
migration_version = 17
width = 1280
height = 1356
window_x = 45
window_y = 45
maximized = False
selected_category = category:all
icon_type_gridview = coverart_big
show_advanced_options = True
auto_update_runtime = False
last_library_sync_at = 1784644598

