--ignore-gpu-blocklist
--enable-gpu-rasterization
--enable-zero-copy
--ozone-platform-hint=auto
--use-gl=angle
--use-angle=vulkan
--enable-features=VaapiVideoDecoder,AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoEncoder,VaapiIgnoreDriverChecks,UseMultiPlaneFormatForHardwareVideo,Vulkan,VulkanFromANGLE,DefaultANGLEVulkan
--oauth2-client-id=77185425430.apps.googleusercontent.com
--oauth2-client-secret=OTJgUOQcT7lO7GsGZq2G4IlT
--disable-breakpad
--no-report-upload
--no-pings
--disable-logging --disable-features=OutdatedBuildDetector,OptimizationGuideOnDeviceModel,Compose,HistoryEmbeddings,TabOrganizer,LensOverlay,ShoppingList,CommercePriceTracking,NtpChromeCartModule,ChromeCartDomBasedHeuristics,PrivacySandboxSettings4,FedCm,ChromeWhatsNew,CustomizeChromeSidePanel
